############################################
# Redis config for local Docker environment
# Edit values here to tune Redis behavior.
############################################

# Network
bind 0.0.0.0
port 6379
protected-mode no
tcp-keepalive 300
timeout 0

# Persistence
dir /data
appendonly yes
appendfsync everysec
save 900 1
save 300 10
save 60 10000

# Memory
maxmemory 256mb
maxmemory-policy allkeys-lru

# Logs
loglevel notice
